# Generated by Django 3.1.2 on 2020-10-22 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(3, 'Invalid product name'), django.core.validators.MaxLengthValidator(55, 'Invalid product name')], verbose_name='Producto')),
                ('value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('discount_value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Invalid stock value')])),
            ],
        ),
    ]
